/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carnets;

import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Optional;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;


public class VentanaLicenciasExpiradas extends javax.swing.JDialog {
    private List<Carnet> carnetsExpirados;
    
    private final DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
    private final VentanaPrincipal ventanaPrincipal = (VentanaPrincipal) this.getParent();
    
    private final DefaultTableModel tabla;
    
    public VentanaLicenciasExpiradas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        tabla = (DefaultTableModel) JTExpirados.getModel();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTDesde = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTHasta = new javax.swing.JTextField();
        jBtBuscar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTExpirados = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Licencias Expiradas");

        jLabel1.setText("Desde");

        jLabel2.setText("Hasta");
        jLabel2.setToolTipText("");

        jBtBuscar.setText("Buscar");
        jBtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtBuscarActionPerformed(evt);
            }
        });

        JTExpirados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", ""},
                {"", ""},
                {"", ""},
                {"", ""},
                {"", ""},
                {"", ""},
                {"", ""},
                {"", ""},
                {"", ""},
                {"", ""},
                {"", ""},
                {"", ""},
                {"", ""},
                {"", ""},
                {"", ""},
                {"", ""}
            },
            new String [] {
                "Nro de Licencia", "Fecha de Expiración"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTExpirados.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        JTExpirados.setPreferredSize(new java.awt.Dimension(372, 240));
        JTExpirados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTExpiradosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTExpirados);
        if (JTExpirados.getColumnModel().getColumnCount() > 0) {
            JTExpirados.getColumnModel().getColumn(0).setResizable(false);
            JTExpirados.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtBuscar)
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jBtBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        jTDesde.getAccessibleContext().setAccessibleName("");
        jTDesde.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtBuscarActionPerformed
        boolean busca = false;
        String desde = jTDesde.getText();
        String hasta = jTHasta.getText();
        
        // LocalDate dF = null;
        // LocalDate hF = null;
        Optional<LocalDate> dFecha = Optional.empty();
        LocalDate hFecha = LocalDate.now().minusDays(1);
        
        try {
            
            if (!desde.equals("")) {
                // dF = LocalDate.parse(desde, formatter);
                dFecha = Optional.of(LocalDate.parse(desde, formatter));
            }
            
            if (!hasta.equals("")) {
                // hF = LocalDate.parse(hasta, formatter);
                hFecha = LocalDate.parse(hasta, formatter);
            } 
            //carnetsExpirados = DAOCarnet.expirados(Optional.of(LocalDate.parse(desde, formatter)), hFecha);
            
            //System.out.println(carnetsExpirados.size());
            
            carnetsExpirados = DAOCarnet.expirados(dFecha, hFecha);

            limpiarTabla();

            for(Carnet item : carnetsExpirados) {
                tabla.addRow(new Object[] {item.getNumero().get(), item.getExpiracion().format(formatter)});
            }
            /*
            tabla.addRow(new Object[] {1, 2});
            tabla.addRow(new Object[] {10, 20});
            tabla.addRow(new Object[] {100, 200});
            */
            rellenarTabla();
            
        } catch (SQLException ex) {
            Logger.getLogger(VentanaLicenciasExpiradas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBtBuscarActionPerformed
        
    private void JTExpiradosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTExpiradosMouseClicked
        
        if (evt.getClickCount() == 2){
            int fila = JTExpirados.getSelectedRow();

            String nro = tabla.getValueAt(fila, 0).toString();
            String fecha = tabla.getValueAt(fila, 1).toString();

            if (!nro.equals("") && !fecha.equals("")) {
                System.out.println(fila + " --> Nro: " + nro + " Fecha: " + fecha);
            }
        }
    }//GEN-LAST:event_JTExpiradosMouseClicked
    
    private void limpiarTabla(){
        int i = 0;
        int filas = tabla.getRowCount();
        
        for (i = 1; i <= filas; i++){
            tabla.removeRow(0);
        }
    }
    
    private void rellenarTabla(){
        int i = 0;
        int filas = tabla.getRowCount();
        
        if (filas < 16){
            for (i = filas; i <= 16; i++){
                tabla.addRow(new Object[] {"", ""});
            }
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaLicenciasExpiradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaLicenciasExpiradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaLicenciasExpiradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaLicenciasExpiradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaLicenciasExpiradas dialog = new VentanaLicenciasExpiradas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTExpirados;
    private javax.swing.JButton jBtBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTDesde;
    private javax.swing.JTextField jTHasta;
    // End of variables declaration//GEN-END:variables
}
